django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
     url(r'^$', 'web.views.home', name='home'),
     url(r'^welcome/$', 'web.views.welcome', name='welcome'),
     url(r'^student-registration/$', 'students.views.student_registration', name='student-registration'),
    # url(r'^knowell/', include('knowell.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/media/images/favicon.ico'}))

from django.conf import settings
#if settings.DEBUG:
urlpatterns += patterns('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}) )
urlpatterns += patterns('',(r'^adminmedia/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.ADMIN_MEDIA_PREFIX}) )

students/models.py
from django.db import models
from storage import upload_storage
from imagekit.models import ImageModel
from south.modelsinspector import add_introspection_rules
from tinymce.models import HTMLField
from decimal import Decimal

from test.models import Test, Section, Standard, Stream
from question.models import Question, Option
# Create your models here.

class Student(models.Model):
    first_name = models.CharField(max_length=30, db_index=True)
    middle_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30)
    registration_number = models.CharField(max_length=10, blank=True, null=True)
    date_of_birth = models.DateTimeField(blank=True, null=True)
    gender = models.CharField(max_length=15, db_index=True, default='male', 
                    choices=(
                        ('male', 'Male'),
                        ('female', 'Female')))
    education_institution = models.CharField(max_length=100, blank=True, null=True)
    standard = models.ForeignKey(Standard, db_index=True)
    stream = models.ForeignKey(Stream, blank=True, null=True)
    last_exam_appeared = models.CharField(max_length=100, blank=True, null=True)
    marks_expected_actual = models.CharField(max_length=100, blank=True, null=True, verbose_name="Marks (Expected/Actual)")
    phone_number = models.CharField(max_length=30, default='')
    email = models.CharField(max_length=200, default='')
    address = models.TextField(blank=True, null=True)
    city = models.CharField(max_length=30, blank=True, null=True)
    pincode = models.IntegerField(max_length=6, blank=True, null=True)
    guardian_name = models.CharField(max_length=30, blank=True, null=True)
    guardian_contact_number = models.CharField(max_length=30, blank=True, null=True)
    career_aspiration_1 = models.CharField(max_length=50, blank=True, null=True, verbose_name="1.")
    career_aspiration_2 = models.CharField(max_length=50, blank=True, null=True, verbose_name="2.")
    career_aspiration_3 = models.CharField(max_length=50, blank=True, null=True, verbose_name="3.")


class StudentTest(models.Model):
    student = models.ForeignKey(Student)
    test = models.ForeignKey(Test)
    created_on = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(blank=True, null=True)
    ended_at = models.DateTimeField(blank=True, null=True)
    total_score = models.IntegerField(max_length=3)
    score_acquired = models.IntegerField(max_length=3, blank=True, null=True)


class StudentTestSectionDetail(models.Model):
    studenttest = models.ForeignKey(StudentTest)
    section = models.ForeignKey(Section)
    time = models.IntegerField(max_length=3, verbose_name="Time (in minutes)", default=Decimal('0')) 
    score = models.IntegerField(max_length=3, default=Decimal('0'))

class StudentTestDetail(models.Model):
    studenttest = models.ForeignKey(StudentTest)
    question = models.ForeignKey(Question)
    question_score = models.IntegerField(max_length=3, blank=True, null=True)
    correct_answer = models.CharField(max_length=100, blank=True, null=True)
    answer = models.CharField(max_length=100, blank=True, null=True)
    answer_score = models.IntegerField(max_length=3, blank=True, null=True)

students/forms.py
from django import forms

from students.models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        self.fields['date_of_birth'].input_formats = ['%d-%m-%Y']

students/views.py
# Create your views here.

from django.shortcuts import render_to_response
from django.template import RequestContext

from random import randint, shuffle

from web.models import Page
from students.models import *
from students.forms import *


def generate_unique_random(total, rmax, rmin=0):
    if total > rmax:
        return []
    i = 0
    arr = []
    while(i < rmax):
        r = randint(rmin, rmax)
        if r not in arr:
            arr.append(r)
            i += 1
    return arr


def student_registration(request):
    form =  StudentForm()
    errors = []
    try:
        page = Page.objects.get(page='student')
    except Page.DoesNotExist:
        page = ''
    if request.method == "POST":
        form = StudentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            obj = form.instance
            obj.registration_number = str(obj.first_name[:3]).lower() + str(randint(1,9999999))
            obj.save()
            stream = obj.stream
            standard = obj.standard
            test = Test.objects.filter(standard=standard, stream=stream, is_active=True)
            if test:
                test = test[0]
                ts = test.testsection_set.all()
                if ts:
                    qdict = {}
                    for t in ts:
                        sec = t.section
                        lod = t.level_of_difficulty
                        tq = t.total_questions
                        questions = Question.objects.filter(section=sec, level_of_difficulty=lod, is_active=True)
                        print "q:::%s" % questions
                        if questions:
                            qlen = len(questions)
                            random = generate_unique_random(tq, qlen-1)
                            q = []
                            for r in random:
                                if sec not in qdict:
                                    qdict[sec] = [questions[r]]
                                else:
                                    qdict[sec].append(questions[r])
                        else:
                            print "No questions"
                    print qdict
                    create_student_test(obj, test, qdict)
                else:
                    print "No sections found"

            else:
                print "No test found"
        else:
            errors = form.errors
            print errors
    ctxt = {
        'form': form,
        'page': page,
        'prev': '/welcome/',
        'next': '',
        'errors': errors
    }
    return render_to_response('students/registration.html',
            ctxt,
            context_instance=RequestContext(request))

templates/students/registration.html
{% extends "web/base.html" %}

{% block css %}
{{block.super}}
    <link href="/media/css/table.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/media/css/nivo-slider.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/media/css/jquery-ui-1.8.2.custom.css" rel="stylesheet" type="text/css" media="screen" />
    <style>
        .table-form input[type="text"] {
            border-radius: 5px;
            height: 20px;
            width: 150px;
        }

        textarea {
            width: 150px;
            border-radius: 5px;
            height: 35px;
        }

        select {
            border-radius: 5px;
            height: 20px;
            width: 150px;
        }
    </style>
{% endblock %}

{% block js %}
{{block.super}}
    <script type="text/javascript" src="/media/js/jquery-ui-1.8.2.custom.min.js" charset="utf-8"></script>
{% endblock %}

{% block page_title %}
    Student Registration
{% endblock %}

{% block content_page_title %}
    {{page.title}}        
{% endblock %}

{% block content_page_description %}
    {% if page.image %}
        <td class="leftcontentnobg" valign="top">
            <img src="{{page.image.url}}" style="width:250px; height:300px;"/>
        </td>
    {% else %}
        <div class="leftcontent">
        {{page.description|safe}}
        </div>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="centerimage1">
        {% if errors %}
            <p class="errornote">
                Please enter all mandatory fields.
            </p>
        {% endif %}
        <table>
            <tr>
                <td>
                    <form name="studreg" id="studreg" action="/student-registration/" method="post">
                        {% csrf_token %}
                        <table width="690px" height="400px" border="0">
                            <tr>
                                <td valign="top">
                                    <table class="table-form">
                                        <th colspan="2" style="font-family:Calibri, 'Lucida Calligraphy', 'Goudy Old Style'; font-size:18px; font-weight:bold; color:#0E86C0;">Personal Information</th>
                                        <tr {% if form.first_name.errors %}class="errors"{% endif %}>
                                            <td class="studregformlabel">{{form.first_name.label}} <span class="red">*</span></td>
                                            <td>{{form.first_name}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.middle_name.label}}</td>
                                            <td>{{form.middle_name}}</td>
                                        </tr>
                                        <tr {% if form.last_name.errors %}class="errors"{% endif %}>
                                            <td class="studregformlabel">{{form.last_name.label}} <span class="red">*</span></td>
                                            <td>{{form.last_name}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.date_of_birth.label}}</td>
                                            <td>{{form.date_of_birth}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.gender.label}}</td>
                                            <td>{{form.gender}}</td>
                                        </tr>
                                        <tr>
                                            <th colspan="2" style="font-family:Calibri, 'Lucida Calligraphy', 'Goudy Old Style'; font-size:18px; font-weight:bold; color:#0E86C0;">Academic Information</th>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.education_institution.label}}</td>
                                            <td>{{form.education_institution}}</td>
                                        </tr>
                                        <tr {% if form.standard.errors %}class="errors"{% endif %}>
                                            <td class="studregformlabel">{{form.standard.label}} <span class="red">*</span></td>
                                            <td>{{form.standard}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.stream.label}}</td>
                                            <td>{{form.stream}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.last_exam_appeared.label}}</td>
                                            <td>{{form.last_exam_appeared}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.marks_expected_actual.label}}</td>
                                            <td>{{form.marks_expected_actual}}</td>
                                        </tr>
                                    </table>
                                </td>
                                <td valign="top">
                                    <table class="table-form">
                                        <th colspan="2" style="font-family:Calibri, 'Lucida Calligraphy', 'Goudy Old Style'; font-size:18px; font-weight:bold; color:#0E86C0;">Contact Details</th>
                                        <tr {% if form.phone_number.errors %}class="errors"{% endif %}>
                                            <td class="studregformlabel">{{form.phone_number.label}} <span class="red">*</span></td>
                                            <td>{{form.phone_number}}</td>
                                        </tr>
                                        <tr {% if form.email.errors %}class="errors"{% endif %}>
                                            <td class="studregformlabel">{{form.email.label}} <span class="red">*</span></td>
                                            <td>{{form.email}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.address.label}}</td>
                                            <td>{{form.address}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.city.label}}</td>
                                            <td>{{form.city}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.pincode.label}}</td>
                                            <td>{{form.pincode}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.guardian_name.label}}</td>
                                            <td>{{form.guardian_name}}</td>
                                        </tr>
                                        <tr>
                                            <td class="studregformlabel">{{form.guardian_contact_number.label}}</td>
                                            <td>{{form.guardian_contact_number}}</td>
                                        </tr>
                                        <tr>
                                            <th colspan="2" style="font-family:Calibri, 'Lucida Calligraphy', 'Goudy Old Style'; font-size:18px; font-weight:bold; color:#0E86C0;">Top 3 Career Aspirations</th>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                {{form.career_aspiration_1.label}} {{form.career_aspiration_1}}<br />
                                                {{form.career_aspiration_2.label}} {{form.career_aspiration_2}}<br />
                                                {{form.career_aspiration_3.label}} {{form.career_aspiration_3}}<br />
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </form>
                </td>
            </tr>
        </table>
    </div>
{% endblock %}

{% block footer %}
<div class="centertimer" align="center">
    <table>
        <tr>
            <td class="leftimage" align="center">
                <a href="{{prev|default:"/"}}"><img src="/media/images/back.png" width="110px" /></a>
            </td>
            <td class="timerimage">
                
            </td>
            <td class="rightimage" align="center">
                <img src="/media/images/Next.png" width="110px" class="submit-form"/>
            </td>
        </tr>
    </table>
</div>
{% endblock %}

{% block script_footer %}
   <script type="text/javascript">
    $(document).ready(function() {
        $(".submit-form").click(function(){
            $("#studreg").submit(); 
        });

        $('#id_date_of_birth').datepicker({dateFormat: 'dd-mm-yy',
            onSelect: function(){
                $('#id_date_of_birth').datepicker('enable');
            },
        });
    });
   </script>
{% endblock %}